name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main

jobs:
  increase_version:
    runs-on: ubuntu-latest
    name: Increase Version Job
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: git config --global user.email "rfoe@gmx.de"
      - run: git config --global user.name "Robert Foerder"
      - run: npm version patch
      - run: git push
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    if: ${{ always() && contains(join(needs.*.result, ','), 'success') }}
    needs: [increase_version]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_BLUE_POND_02B563803 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: 'upload'
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: '/' # App source code path
          api_location: '' # Api source code path - optional
          output_location: 'dist/apps/finance-fe' # Built app content directory - optional
          ###### End of Repository/Build Configurations ######
